image: gitpod/workspace-full:latest
ports:
  - port: 8080
checkoutLocation: "src/github.com/raghuP9/go-endpoint"
workspaceLocation: "."
tasks:
  - init: >
      cd /workspace/src/github.com/raghuP9/go-endpoint &&
      go get -v ./... &&
      go build -o app
